// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Build-on-demand patched OpenShell cluster image.
//
// Docker 26+ flips the install-time default storage driver from the legacy
// `overlay2` graph driver to the new containerd image-store with `overlayfs`
// snapshotter. K3s inside the OpenShell cluster container relies on the host
// overlayfs supporting nested overlay mounts, which the new snapshotter does
// not. The kernel rejects the nested mount with EINVAL ("invalid argument"),
// k3s loops, and the gateway never reaches healthy.
//
// Upstream OpenShell closed this class of bug wontfix while a multi-month
// roadmap migration off k3s lands. NemoClaw downstream cannot wait. This
// module produces a locally-built drop-in replacement for the cluster image
// that routes around the kernel limitation by selecting `fuse-overlayfs` (or
// `native`) as the k3s snapshotter and installing the userspace
// fuse-overlayfs binary.
//
// The patched image is built on the user's machine via `docker build` from
// the upstream image plus a tiny Dockerfile fragment. We do not publish the
// patched image; the cache is the user's local Docker engine.

import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

export type SnapshotterChoice = "fuse-overlayfs" | "native";

export const DEFAULT_SNAPSHOTTER: SnapshotterChoice = "fuse-overlayfs";

const TAG_PREFIX = "nemoclaw-cluster";

export interface PatchFsApi {
  mkdtempSync: (prefix: string) => string;
  writeFileSync: (filePath: string, data: string, encoding: BufferEncoding) => void;
  rmSync: (filePath: string, options?: { recursive?: boolean; force?: boolean }) => void;
}

export interface RunOpts {
  ignoreError?: boolean;
  /** Hard wall-clock timeout (ms). Child is killed on expiry. */
  timeoutMs?: number;
}

export interface EnsurePatchedClusterImageOpts {
  /** Upstream OpenShell cluster image reference, e.g. `ghcr.io/nvidia/openshell/cluster:0.0.36`. */
  upstreamImage: string;
  /** Snapshotter to bake into the patched image's k3s CMD. Defaults to fuse-overlayfs. */
  snapshotter?: SnapshotterChoice;
  /** Captures stdout from a command (used to probe `docker image inspect`). */
  runCaptureImpl?: (cmd: readonly string[], opts?: RunOpts) => string;
  /** Streams a command's stdio (used for `docker pull` and `docker build`). */
  runImpl?: (cmd: readonly string[], opts?: RunOpts) => { status: number | null };
  /** Logger for human-readable progress lines. Defaults to console.error. */
  logger?: (msg: string) => void;
  /** Filesystem implementation (testing seam). */
  fsImpl?: PatchFsApi;
  /** Temp dir resolver (testing seam). */
  tmpdirImpl?: () => string;
  /**
   * Hard wall-clock timeout (ms) for `docker pull`. spawnSync has no native
   * timeout safety on its own, and a stuck registry on this critical path
   * would hang the entire onboard. Default 10 minutes.
   */
  pullTimeoutMs?: number;
  /**
   * Hard wall-clock timeout (ms) for `docker build`. The patched image is
   * tiny (one apt-get layer + CMD) so 5 minutes is generous. Default 5 minutes.
   */
  buildTimeoutMs?: number;
}

/** 10 minutes — generous for a slow registry, short enough to fail fast on a hung daemon. */
export const DEFAULT_PULL_TIMEOUT_MS = 10 * 60 * 1000;
/** 5 minutes — a one-layer apt-get build should complete in seconds. */
export const DEFAULT_BUILD_TIMEOUT_MS = 5 * 60 * 1000;

/**
 * Pinned static fuse-overlayfs release. Static binaries from the upstream
 * containers/fuse-overlayfs project bundle libfuse, so they work in minimal
 * base images that lack `libfuse3.so.3`.
 *
 * Bump in lockstep with upstream releases. The repo's installer-hash-check
 * CI job catches drift if these get out of sync with anything else that
 * pins the same version.
 */
export const FUSE_OVERLAYFS_VERSION = "v1.14";

/** Returns the Dockerfile contents used to patch a single upstream cluster image. */
export function buildPatchDockerfile(snapshotter: SnapshotterChoice): string {
  // The upstream entrypoint (cluster-entrypoint.sh) does
  // `exec /bin/k3s "$@" ...kubelet args...`, so CMD becomes the k3s
  // positional args. Override CMD to inject `--snapshotter=...` before the
  // entrypoint's appended kubelet args so k3s picks the requested snapshotter.
  //
  // We deliberately do NOT use `apt-get install fuse-overlayfs`: the upstream
  // cluster image's base ships BusyBox `tar` rather than GNU `tar`, so
  // `dpkg-deb` cannot extract any `.deb` (it invokes tar with options
  // BusyBox doesn't recognize, e.g. `--warning=no-timestamp`). The supported
  // path is to drop in the official static binary from
  // containers/fuse-overlayfs (single statically-linked file, ~500 KB).
  return [
    "# Generated by NemoClaw — see src/lib/cluster-image-patch.ts.",
    "ARG UPSTREAM",
    "FROM ${UPSTREAM}",
    "USER root",
    "ARG TARGETARCH=amd64",
    `ARG FUSE_OVERLAYFS_VERSION=${FUSE_OVERLAYFS_VERSION}`,
    'RUN set -eux; \\',
    '    case "$TARGETARCH" in \\',
    "      amd64) FUSE_ARCH=x86_64 ;; \\",
    "      arm64) FUSE_ARCH=aarch64 ;; \\",
    '      *) echo "Unsupported TARGETARCH: $TARGETARCH" >&2; exit 1 ;; \\',
    "    esac; \\",
    '    curl -fsSL "https://github.com/containers/fuse-overlayfs/releases/download/${FUSE_OVERLAYFS_VERSION}/fuse-overlayfs-${FUSE_ARCH}" \\',
    "      -o /usr/local/bin/fuse-overlayfs; \\",
    "    chmod +x /usr/local/bin/fuse-overlayfs; \\",
    "    /usr/local/bin/fuse-overlayfs --version",
    `CMD ["server", "--snapshotter=${snapshotter}"]`,
    "",
  ].join("\n");
}

/**
 * Strips registry prefix and digest, returning the version portion of a tag.
 * A colon only delimits a tag when it appears after the last path separator —
 * references like `registry:5000/repo` (registry with explicit port, no tag)
 * must not be parsed as if `5000/repo` were the tag.
 */
export function extractUpstreamVersion(upstreamImage: string): string {
  const withoutDigest = upstreamImage.split("@")[0] ?? "";
  const lastSlash = withoutDigest.lastIndexOf("/");
  const lastColon = withoutDigest.lastIndexOf(":");
  if (lastColon > lastSlash && lastColon < withoutDigest.length - 1) {
    return withoutDigest.slice(lastColon + 1);
  }
  return "unknown";
}

/** Deterministic local image tag derived from upstream version, snapshotter, and Dockerfile content. */
export function computePatchedTag(opts: {
  upstreamImage: string;
  snapshotter: SnapshotterChoice;
  dockerfile: string;
}): string {
  const version = extractUpstreamVersion(opts.upstreamImage);
  const sha = crypto
    .createHash("sha256")
    .update(`${opts.upstreamImage}\n${opts.snapshotter}\n${opts.dockerfile}`)
    .digest("hex")
    .slice(0, 8);
  return `${TAG_PREFIX}:${version}-${opts.snapshotter}-${sha}`;
}

/**
 * Idempotently produce a locally-built patched cluster image and return its
 * tag. Subsequent calls with the same inputs no-op via the local Docker cache.
 *
 * Throws on build failure with a structured error so callers can fall back to
 * the upstream image (and the upstream's eventual k3s crash) or surface the
 * documented manual workaround.
 */
export function ensurePatchedClusterImage(opts: EnsurePatchedClusterImageOpts): string {
  const snapshotter = opts.snapshotter ?? DEFAULT_SNAPSHOTTER;
  const log = opts.logger ?? ((msg: string) => console.error(msg));
  const runCaptureImpl = opts.runCaptureImpl ?? defaultRunCapture;
  const runImpl = opts.runImpl ?? defaultRun;
  const fsApi: PatchFsApi = opts.fsImpl ?? {
    mkdtempSync: (prefix: string) => fs.mkdtempSync(prefix),
    writeFileSync: (filePath: string, data: string, encoding: BufferEncoding) =>
      fs.writeFileSync(filePath, data, encoding),
    rmSync: (filePath: string, options) => fs.rmSync(filePath, options),
  };
  const tmpdirImpl = opts.tmpdirImpl ?? os.tmpdir;
  const pullTimeoutMs = opts.pullTimeoutMs ?? DEFAULT_PULL_TIMEOUT_MS;
  const buildTimeoutMs = opts.buildTimeoutMs ?? DEFAULT_BUILD_TIMEOUT_MS;

  const dockerfile = buildPatchDockerfile(snapshotter);
  const tag = computePatchedTag({
    upstreamImage: opts.upstreamImage,
    snapshotter,
    dockerfile,
  });

  if (imageExists(tag, runCaptureImpl)) {
    return tag;
  }

  log(`  Building patched cluster image (one-time) → ${tag}`);
  log(`  Source: ${opts.upstreamImage}`);
  log(`  Snapshotter: ${snapshotter}`);

  const pullResult = runImpl(["docker", "pull", opts.upstreamImage], {
    ignoreError: true,
    timeoutMs: pullTimeoutMs,
  });
  if (pullResult.status !== 0) {
    throw new ClusterImagePatchError(
      `failed to pull upstream cluster image ${opts.upstreamImage} ` +
        `(docker pull exit ${pullResult.status}; timeout ${pullTimeoutMs} ms)`,
    );
  }

  const tmpDir = fsApi.mkdtempSync(path.join(tmpdirImpl(), "nemoclaw-cluster-patch-"));
  try {
    const dockerfilePath = path.join(tmpDir, "Dockerfile");
    fsApi.writeFileSync(dockerfilePath, dockerfile, "utf-8");

    const buildResult = runImpl(
      [
        "docker",
        "build",
        "--build-arg",
        `UPSTREAM=${opts.upstreamImage}`,
        "-t",
        tag,
        tmpDir,
      ],
      { ignoreError: true, timeoutMs: buildTimeoutMs },
    );

    if (buildResult.status !== 0) {
      throw new ClusterImagePatchError(
        `failed to build patched cluster image ` +
          `(docker build exit ${buildResult.status}; timeout ${buildTimeoutMs} ms)`,
      );
    }
  } finally {
    try {
      fsApi.rmSync(tmpDir, { recursive: true, force: true });
    } catch {
      // Best-effort cleanup; don't mask the build outcome with a tmp-cleanup error.
    }
  }

  log(`  Patched image ready: ${tag}`);
  return tag;
}

function imageExists(
  tag: string,
  runCaptureImpl: (cmd: readonly string[], opts?: RunOpts) => string,
): boolean {
  const out = runCaptureImpl(["docker", "image", "inspect", "--format", "{{.Id}}", tag], {
    ignoreError: true,
  });
  return Boolean(out && out.trim());
}

export class ClusterImagePatchError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ClusterImagePatchError";
  }
}

const runner: typeof import("./runner") = require("./runner");

function defaultRunCapture(cmd: readonly string[], opts: RunOpts = {}): string {
  return runner.runCapture(cmd, {
    ignoreError: opts.ignoreError,
    ...(opts.timeoutMs !== undefined ? { timeout: opts.timeoutMs } : {}),
  });
}

function defaultRun(cmd: readonly string[], opts: RunOpts = {}): { status: number | null } {
  const result = runner.run(cmd, {
    ignoreError: opts.ignoreError,
    ...(opts.timeoutMs !== undefined ? { timeout: opts.timeoutMs } : {}),
  });
  return { status: result.status ?? null };
}
